mkdir   approval
mkdir   approval_adjustment
mkdir    athaangSI
mkdir      backup
mkdir    bootstrap
mkdir    budget
mkdir    budget_proposal
mkdir    build
mkdir  dashboard
mkdir   dashboard-ori
mkdir   data_athaang
mkdir      dist
mkdir    dms
mkdir    documentation
mkdir    fpdf
mkdir    goods_issue_note
mkdir   grn
mkdir     html2pdf
mkdir   img
mkdir     ipc
mkdir     pages
mkdir     payment
mkdir     petty
mkdir     PHPMailer-master
mkdir   plugins
mkdir    product
mkdir     provisional_jv
mkdir    purchase_order
mkdir     purchase_requisition
mkdir      report
mkdir    revenue_jv
mkdir     setting
mkdir    supp_invoice
mkdir   tally_sample
mkdir    tender
mkdir     travel_approval
mkdir     vendor
mkdir    xampp
mkdir     zoho

